require('./gulp/compile.task');
require('./gulp/page_templates.task');
require('./gulp/component_templates.task');
require('./gulp/my_widgets_templates.task');
require('./gulp/all_in_one_templates.task');
require('./gulp/client_js.task');
require('./gulp/styles.task');
require('./gulp/resources.task');
require('./gulp/build.task');